server:
  port: 8888
spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:http://localhost:8887
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
