spring:
  cloud:
#    gateway:
#      routes:
#        - id : r1
#          uri: lb://customer-service
#          predicates:
#            - Path= /customers/**
#        - id : r2
#          uri: lb://inventory-service
#          predicates:
#            - Path= /products/**
    discovery:
      enabled: true
  application:
    name: gateway-service
server:
  port: 8888

#Configuration dynamique